return {
    ensure_installed = {
      'ansible-language-server',
      'ansible-lint',
      'omnisharp',
      'csharpier',
      'clangd',
      'clang-format',
      'csharpier',
      'templ',
      'html-lsp',
      'prettier',
      'tailwindcss-language-server',
      'typescript-language-server',
      'css-lsp',
      'lua-language-server',
      'codelldb',
      'gopls',
      'gofumpt',
      'goimports-reviser',
      'htmx-lsp',
      'rust-analyzer',
      'angular-language-server',
      'pyright',
      'asm-lsp',
      'autotools-language-server',
      'marksman',
      'protolint'
    },
    auto_update = true,
    run_on_start = true,
    debounce_hours = 2,
}
